import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import { fetchPlans } from "@/lib/plans";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const tempuserid = '1'
  const plans = await fetchPlans();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar userId={tempuserid} plans={plans} />
        {children}
      </body>
    </html>
  );
}
